version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: perfulandia-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api-gateway:
    build: ./microservicio-api-gateway
    container_name: perfulandia-api-gateway
    ports:
      - "9090:8080"
    depends_on:
      - mysql

  catalogo:
    build: ./microservicio-catalogo
    container_name: perfulandia-catalogo
    ports:
      - "9091:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_catalogo?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  usuario:
    build: ./microservicio-usuario
    container_name: perfulandia-usuario
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_usuario?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  sucursal:
    build: ./microservicio-sucursal
    container_name: perfulandia-sucursal
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_sucursal?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  proveedor:
    build: ./microservicio-proveedor
    container_name: perfulandia-proveedor
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_proveedor?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  inventario:
    build: ./microservicio-inventario
    container_name: perfulandia-inventario
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_inventario?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  carrito:
    build: ./microservicio-carrito
    container_name: perfulandia-carrito
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_carrito?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  envios:
    build: ./microservicio-envios
    container_name: perfulandia-envios
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_envios?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  resenas:
    build: ./microservicio-resenas
    container_name: perfulandia-resenas
    ports:
      - "8088:8088"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_reviews?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  cliente:
    build: ./microservicio-cliente
    container_name: perfulandia-cliente
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_cliente?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

  promocion:
    build: ./microservicio-promocion
    container_name: perfulandia-promocion
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/perfulandia_promocion?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - mysql

volumes:
  mysql_data:
