server:
  port: 8093

spring:
  application:
    name: microservicio-api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
              - OPTIONS
      routes:
        - id: microservicio-carrito
          uri: http://carrito:8086
          predicates:
            - Path=/api/carrito/**, /api/carritos/**, /api/pedidos/**, /api/ventas/**
        - id: microservicio-catalogo
          uri: http://catalogo:8081
          predicates:
            - Path=/api/catalogo/**, /api/catalog/**, /api/productos/**, /api/categorias/**, /api/marcas/**
        - id: microservicio-cliente
          uri: http://cliente:8089
          predicates:
            - Path=/api/clientes/**, /api/customers/**
        - id: microservicio-inventario
          uri: http://inventario:8085
          predicates:
            - Path=/api/inventario/**
        - id: microservicio-promocion
          uri: http://promocion:8090
          predicates:
            - Path=/api/promociones/**, /api/promotions/**
        - id: microservicio-proveedor
          uri: http://proveedor:8084
          predicates:
            - Path=/api/proveedores/**
        - id: microservicio-resenas
          uri: http://resenas:8088
          predicates:
            - Path=/api/resenas/**, /api/reviews/**
        - id: microservicio-sucursal
          uri: http://sucursal:8083
          predicates:
            - Path=/api/sucursales/**
        - id: microservicio-usuario
          uri: http://usuario:8082
          predicates:
            - Path=/api/usuarios/**, /api/auth/**
        - id: microservicio-envios
          uri: http://envios:8087
          predicates:
            - Path=/api/envios/**
